# 定义 stages
stages:
  - test
  - publish
  - deploy
  - cleanup
variables:
  # 项目唯一标识
  PROJECT_INDEX: ${CI_PROJECT_NAME}${CI_COMMIT_SHA}
  DEV_IMAGE_NAME: gitlab.yilumofang.com:4567/${CI_PROJECT_PATH}/image

# 单元测试
test_job:
  stage: test
  script:
    - docker-compose -p ${PROJECT_INDEX} up -d php
    - sleep 120
    - docker-compose -p ${PROJECT_INDEX} run --rm -w /data1/htdocs/${CI_PROJECT_NAME}/test/ php phpunit
  only:
    - master
  tags:
    - CI

# 推送镜像到线下代码仓库
publish_offline:
  stage: publish
  script:
    - docker build --no-cache -t ${DEV_IMAGE_NAME}:${CI_COMMIT_SHA} .
    - sh /data/gitlab/bin/push.sh ${DEV_IMAGE_NAME}:${CI_COMMIT_SHA} dev
    - docker tag ${DEV_IMAGE_NAME} ${PRDUCTION_IMAGE_NAME}:latest
    - sh /data/gitlab/bin/push.sh ${PRDUCTION_IMAGE_NAME}:latest product
  only:
    - master
  tags:
    - CI


# 将镜像发布到生产仓库
publish_online:
  stage: publish
  script:
      - docker pull ${DEV_IMAGE_NAME}
      - docker tag ${DEV_IMAGE_NAME} ${PRDUCTION_IMAGE_NAME}:${CI_COMMIT_SHA}
      - sh /data/gitlab/bin/push.sh ${PRDUCTION_IMAGE_NAME}:${CI_COMMIT_SHA} product
      - docker tag ${DEV_IMAGE_NAME} ${PRDUCTION_IMAGE_NAME}:latest
      - sh /data/gitlab/bin/push.sh ${PRDUCTION_IMAGE_NAME}:latest product
  after_script:
      - docker rmi ${PRDUCTION_IMAGE_NAME}:${CI_COMMIT_SHA}
  environment:
    name: production
    when: manual
  only:
    - production
  tags:
    - CD

# 更新测试环境的代码
deploy_test:
  stage: deploy
  script:
    - docker-compose -f /data/test/${CI_PROJECT_NAME}/docker-compose.yml stop php
    - docker-compose -f /data/test/${CI_PROJECT_NAME}/docker-compose.yml rm -f php
    - docker-compose -f /data/test/${CI_PROJECT_NAME}/docker-compose.yml up -d php
  only:
    - master
  tags:
    - CI

# 清理ci过程中产生的环境
cleanup_job:
  stage: cleanup
  script:
    - docker-compose -p ${PROJECT_INDEX} down
    - docker rmi ${PROJECT_INDEX}_php
    - docker rmi ${DEV_IMAGE_NAME}:${CI_COMMIT_SHA}
  when: always
  only:
    - master
  tags:
    - CI