version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./build/nginx/vhosts/@appname@.conf:/etc/nginx/conf.d/@appname@.conf
      - ./build/nginx/fastcgi_params:/etc/nginx/fastcgi_params
    links:
      - php

  php:
    build: .
    command: php-fpm
    volumes:
      - .:/data1/htdocs/@appname@
    links:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: @db_root_pwd@
      MYSQL_DATABASE: @appname@
    volumes:
      - ./build/sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine