version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./build/nginx/vhosts/${PROJECT_NAME}.conf:/etc/nginx/conf.d/${PROJECT_NAME}.conf
      - ./build/nginx/fastcgi_params:/etc/nginx/fastcgi_params
    links:
      - php

  php:
    build: .
    command: php-fpm
    restart: always
    volumes:
      - .:/data1/htdocs/${PROJECT_NAME}
      - /tmp/logs:/data1/logs
    links:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${PROJECT_NAME}
    volumes:
      - ./build/sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    restart: always

  phpunit:
      image: ifintech/php
      command: phpunit
      volumes:
        - .:/data1/htdocs/${PROJECT_NAME}
      links:
        - mysql
        - redis