version: "3"
services:
  nginx:
    image: ifintech/nginx-php
    ports:
      - "80:80"
    environment:
      APP_NAME: @appname@
    links:
      - @appname@_php

  @appname@_php:
    build: .
    command: php-fpm
    volumes:
      - .:/data1/htdocs/@appname@
    links:
      - @appname@_mysql
      - @appname@_redis

  @appname@_mysql:
    image: mysql:5.7
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: @db_root_pwd@
      MYSQL_DATABASE: @appname@
    volumes:
      - ./build/sql:/docker-entrypoint-initdb.d

  @appname@_redis:
    image: redis:alpine